version: '3.3'

services:
  backend-scales-rk:
    build: docker/php
    container_name: backend-scales-rk
    working_dir: /var/www/
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./backend/:/var/www/
      - ./docker/php/logs/:/var/log/php/
    depends_on:
      - mysql-scales-rk
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=PHPSTORM
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cron-scales-rk:
    build: docker/cron
    container_name: cron-scales-rk
    working_dir: /var/www/
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./backend/:/var/www/
      - ./docker/php/logs/:/var/log/php/
    depends_on:
      - backend-scales-rk
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=PHPSTORM

  # docker exec -it supervisor /bin/sh
  supervisor:
    build:
      context: .
      dockerfile: docker/supervisor/supervisor.dockerfile
    container_name: supervisor
    volumes:
      - ./backend:/var/www
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=PHPSTORM
    depends_on:
      - backend-scales-rk
      - mysql-scales-rk

  nginx-scales-rk:
    image: nginx:1.21.1
    container_name: nginx-scales-rk
    ports:
      - 81:80
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./docker/nginx/htpasswd/:/etc/nginx/htpasswd
      - ./docker/nginx/templates/:/etc/nginx/templates
      - ./docker/nginx/logs/:/var/log/nginx
      - ./backend/:/var/www
    depends_on:
      - backend-scales-rk
    environment:
      NGINX_UPSTREAM: backend-scales-rk:9000

  mysql-scales-rk:
    image: mysql:8.0.26
    container_name: mysql-scales-rk
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/mysql/:/var/lib/mysql:rw
      - ./docker/mysql/logs/:/var/log/mysql:rw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=000000
      - MYSQL_DATABASE=docker-boilerplate
      - MYSQL_USER=docker-boilerplate
      - MYSQL_PASSWORD=docker-boilerplate

  phpmyadmin-scales-rk:
    image: phpmyadmin
    container_name: phpmyadmin-scales-rk
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql-scales-rk
